// <auto-generated />
using System;
using BackendAppBilling.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendAppBilling.Migrations
{
    [DbContext(typeof(DbbillingContext))]
    partial class DbbillingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendAppBilling.Models.Billing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("createdAt")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("deletedAt");

                    b.Property<int>("IdCustomer")
                        .HasColumnType("int")
                        .HasColumnName("idCustomer");

                    b.HasKey("Id")
                        .HasName("PK__billings__3213E83F9A5B7E44");

                    b.HasIndex("IdCustomer");

                    b.ToTable("billings", (string)null);
                });

            modelBuilder.Entity("BackendAppBilling.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__customer__3213E83F3C5D64CF");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("BackendAppBilling.Models.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdBilling")
                        .HasColumnType("int")
                        .HasColumnName("idBilling");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int")
                        .HasColumnName("idProduct");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("PK__details__3213E83F22CA75F7");

                    b.HasIndex("IdBilling");

                    b.HasIndex("IdProduct");

                    b.ToTable("details", (string)null);
                });

            modelBuilder.Entity("BackendAppBilling.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("Price")
                        .HasColumnType("int")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("int")
                        .HasColumnName("stock");

                    b.HasKey("Id")
                        .HasName("PK__products__3213E83F123C0D97");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("BackendAppBilling.Models.Billing", b =>
                {
                    b.HasOne("BackendAppBilling.Models.Customer", "IdCustomerNavigation")
                        .WithMany("Billings")
                        .HasForeignKey("IdCustomer")
                        .IsRequired()
                        .HasConstraintName("fk_customers");

                    b.Navigation("IdCustomerNavigation");
                });

            modelBuilder.Entity("BackendAppBilling.Models.Detail", b =>
                {
                    b.HasOne("BackendAppBilling.Models.Billing", "IdBillingNavigation")
                        .WithMany("Details")
                        .HasForeignKey("IdBilling")
                        .IsRequired()
                        .HasConstraintName("fk_billings");

                    b.HasOne("BackendAppBilling.Models.Product", "IdProductNavigation")
                        .WithMany("Details")
                        .HasForeignKey("IdProduct")
                        .IsRequired()
                        .HasConstraintName("fk_products");

                    b.Navigation("IdBillingNavigation");

                    b.Navigation("IdProductNavigation");
                });

            modelBuilder.Entity("BackendAppBilling.Models.Billing", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("BackendAppBilling.Models.Customer", b =>
                {
                    b.Navigation("Billings");
                });

            modelBuilder.Entity("BackendAppBilling.Models.Product", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
